### ISSUE TITLE
Scroll Animations - Other

### ISSUE THREAD

**Issue by mikezens** [jcaustrita/tribe#10]
@jcaustrita 

Are there more scroll animations that are needed? At the moment I just have story on my list.

**Comment by jcaustrita** [comment]
@mikezens maybe we can have the SVGs on the homepage (that module) slide up into place as they come into view? that could be cool.

**Comment by mikezens** [comment]
@jcaustrita 

Ok, one thing to note, this style would be added to anywhere the module is used unless there is a setting in Modx to turn it off per-module.

Are there any other animations you want to use on any other modules? Fade-in of text/images, etc...?

**Comment by jcaustrita** [comment]
@mikezens yup, i get that. as far as any other animations, just the animation stuff we discussed with the H1 and the story module.

**Comment by mikezens** [comment]
@jcaustrita How was the H1 supposed to be animated again, I forgot that detail.

**Comment by jcaustrita** [comment]
@mikezens we discussed this menu animation for the menu: http://www.giampierocruceli.com

and the h1 to fade/slide up into place.

**Comment by mikezens** [comment]
Ok, sounds good. I had the link for the menu.
