### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by mikezens** [jcaustrita/tribe#13]
@jcaustrita @pmh1 

I'm trying to push my latest code but am getting an error. I think it might be a permissions issue with the repo. Any thoughts?

![screen shot 2017-06-05 at 10 39 29 pm](https://cloud.githubusercontent.com/assets/6498265/26814086/e3e660e4-4a3f-11e7-9f6e-4812d9473a79.png)

**Comment by jcaustrita** [comment]
@mikezens is it because you're still pending as a collaborator? 
<img width="748" alt="screen shot 2017-06-05 at 9 41 29 pm" src="https://cloud.githubusercontent.com/assets/13442924/26814115/d459a88c-4a37-11e7-8b5d-04670a31330d.png">

**Comment by mikezens** [comment]
@jcaustrita Yup, that was it, I thought I accepted it before.
