### ISSUE TITLE
Products - Top Bar Color

### ISSUE THREAD

**Issue by mikezens** [jcaustrita/tribe#3]
@jcaustrita 

What color should the bar be in each theme? The themes are default, gray, dark gray.

**Comment by jcaustrita** [comment]
@mikezens what bar?

**Comment by mikezens** [comment]
@jcaustrita The in this example, the black the first row over the featured / products are overlapping.

<img width="892" alt="screen shot 2017-05-30 at 8 44 44 pm" src="https://cloud.githubusercontent.com/assets/6498265/26613639/f8c00ce8-4578-11e7-9ee0-a959bdf0f2d1.png">

**Comment by jcaustrita** [comment]
@mikezens we discussed this on the phone... you mentioned it was gonna be a color input (assuming hex). that not right?

**Comment by mikezens** [comment]
I remember discussing it but forgot the details. Yea, that sounds right, I'll configure it this way.
