### ISSUE TITLE
Quote Rotator - Auto Rotate Timer

### ISSUE THREAD

**Issue by mikezens** [jcaustrita/tribe#7]
@jcaustrita 

1. What is the time between each slide auto rotating?
2. Should the rotation pause when a user hovers over the slide?

**Comment by jcaustrita** [comment]
5 seconds. no pause. good questions :)

**Comment by mikezens** [comment]
Ok, great.

Just fyi, here is the rotator I like to use (http://kenwheeler.github.io/slick/). You can see the available settings on the page if your ever curious.
