### ISSUE TITLE
Full Width Video - Max Width Setting

### ISSUE THREAD

**Issue by mikezens** [jcaustrita/tribe#9]
@jcaustrita 

What do you think about having a max width instead of going full width? It prevents the video from getting too tall for the viewport.

![screen shot 2017-05-29 at 10 57 50 pm](https://cloud.githubusercontent.com/assets/6498265/26568730/0b128a62-44c3-11e7-8013-1d7303baa747.png)

**Comment by jcaustrita** [comment]
@mikezens hmmm... sure. lets try that.

**Comment by mikezens** [comment]
Ok, cool. On previous projects it is just something I've seen that can be problematic with large screens.
